name: FengYun27-sync
on:
  schedule:
    - cron: '4 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-FengYun27-Sheep_Hair
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync FengYun27-Sheep_Hair
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/FengYun27/Sheep_Hair.git"
          source_branch: "main"
          destination_branch: "FengYun27"
          github_token: ${{ secrets.PAT }}
