name: yml-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-yml-JavaScript-yml
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync yml-JavaScript-yml
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "http://yml-gitea.ml:2233/yml/JavaScript-yml.git"
          source_branch: "master"
          destination_branch: "yml"
          github_token: ${{ secrets.PAT }}
